services:
  - type: web
    name: directus-4profi
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        value: dpg-...oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: directus_pnkw
      - key: DB_USER
        value: directus_user
      - key: DB_PASSWORD
        value: ...
      - key: DB_SSL
        value: true
      - key: CORS_ENABLED
        value: true
      - key: CORS_ORIGIN
        value: "*"
    disk:
      name: directus_disk
      mountPath: /data
      sizeGB: 1
